#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Token {
    // Stage 1
    Keyword(Keywords),
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    Semicolon,
    Integer(u64),
    Identifier(String),
    // Stage 2 (Unary ops)
    Minus,
    ExclamationPoint,
    Tilde,
    // Stage 3 (Binary ops)
    Plus,
    Star,
    Slash,
    // Stage 4 (Logical binary ops)
    LogicalAnd,
    LogicalOr,
    DoubleEquals,
    NotEquals,
    LessThan,
    LessThanEquals,
    GreaterThan,
    GreaterThanEquals,
    // Stage 5 (Local variables)
    SingleEquals,
    // Tons of remaining ops
    Increment,
    Decrement,
    PercentSign,
    BitwiseLeftShift,
    BitwiseRightShift,
    SingleAnd,
    BitwiseXor,
    BitwiseOr,
    QuestionMark,
    Colon,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    PercentEquals,
    BitwiseLeftShiftEquals,
    BitwiseRightShiftEquals,
    BitwiseAndEquals,
    BitwiseXorEquals,
    BitwiseOrEquals,
    Comma,
    Period,
    Arrow,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, strum_macros::EnumString)]
#[strum(serialize_all = "lowercase")]
pub enum Keywords {
    Auto,
    Break,
    Case,
    Char,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extern,
    Float,
    For,
    Goto,
    If,
    Inline,
    Int,
    Long,
    Nullptr,
    Register,
    Restrict,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    Struct,
    Switch,
    Typedef,
    Union,
    Unsigned,
    Void,
    Volatile,
    While,
}
